apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-manager
  name: kafka-manager
spec:
  ports:
  - port: 9000
    name: app
    protocol: TCP
    targetPort: 9000
  selector:
    app: kafka-manager
