---
# Source: kafka-manager/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dev-kafka-manager
  labels:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/version: 1.3.3.22
    helm.sh/chart: kafka-manager-2.2.0
type: Opaque
data:
  
  applicationSecret: "SEpRdUJlZ1hYbA=="
  
  basicAuthUsername:  "YWRtaW4="
  
  basicAuthPassword: "WGNxOXp0blNvcg=="
  

---
# Source: kafka-manager/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/version: 1.3.3.22
    helm.sh/chart: kafka-manager-2.2.0
  name: dev-kafka-manager

---
# Source: kafka-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dev-kafka-manager
  labels:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/version: 1.3.3.22
    helm.sh/chart: kafka-manager-2.2.0
spec:
  type: ClusterIP
  ports:
    - name: kafka-manager
      port: 9000
      targetPort: kafka-manager
      protocol: TCP
  selector:
    app: kafka-manager
    release: dev

---
# Source: kafka-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-kafka-manager
  labels:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-manager
    app.kubernetes.io/version: 1.3.3.22
    helm.sh/chart: kafka-manager-2.2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
      release: dev
  template:
    metadata:
      labels:
        app: kafka-manager
        release: dev
    spec:
      serviceAccountName: dev-kafka-manager
      containers:
        - name: kafka-manager
          image: "zenko/kafka-manager:1.3.3.22"
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka-manager
              containerPort: 9000
              protocol: TCP
          env:
            - name: ZK_HOSTS
              value: "dev-zookeeper:2181"
            - name: JAVA_OPTS
              value: 
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-kafka-manager
                  key: applicationSecret
            - name: KAFKA_MANAGER_AUTH_ENABLED
              value: "false"
            - name: KAFKA_MANAGER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dev-kafka-manager
                  key: basicAuthUsername
            - name: KAFKA_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-kafka-manager
                  key: basicAuthPassword
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: kafka-manager
            initialDelaySeconds: 60
            timeoutSeconds: 30
            
          readinessProbe:
            httpGet:
              path: /api/health
              port: kafka-manager
            
          resources:
            {}
            

---
# Source: kafka-manager/templates/configmap.yaml

---
# Source: kafka-manager/templates/ingress.yaml


---
# Source: kafka-manager/templates/job.yaml

