apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-example
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: nodejs-example:local
        imagePullPolicy: Never
