apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  namespace: default
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80
