bases:
- ../../../local/metallb/kustomize/base
- ../../../ingress-controller/kong-ingress-controller/kustomize/overlays/local
- ../../../monitoring/weave-scope/kustomize/overlays/local
- ../../../monitoring/kubernetes-dashboard/kustomize/base
- ../../../monitoring/kafka/kustomize/base
- ../../../middleware/kafka/kustomize/overlays/local
- ../../../middleware/redis/kustomize/base
- ../../../applications/echo-server/kustomize/overlays/local
- ../../../applications/nodejs-example/kustomize/overlays/local
